## Project 1: Generate Parallel Databases

Key to the definition of differenital privacy is the ability to ask the question "When querying a database, if I removed someone from the database, would the output of the query be any different?". Thus, in order to check this, we must construct what we term "parallel databases" which are simply databases with one entry removed. 

In this first project, I want you to create a list of every parallel database to the one currently contained in the "db" variable. Then, I want you to create a function which both:

- creates the initial database (db)
- creates all parallel databases

In [1]:
import torch
# the number of entries in our database
num_entries = 5000
db = torch.rand(num_entries) > 0.5

In [2]:
def get_parallel_db(db, remove_index):
    """Returns a parallel database by removing
    one sample from a given index
    
    Args:
        db (tensor): The original database.
        remove_index (int): specifies which sample to remove.

    Returns:
        tensor: a pararllel database.
    """
    # TODO: Remove one sample from the database using the remove_index
    
    parallel_db = torch.cat((db[0:remove_index], 
                             db[remove_index+1:]))
    return parallel_db

get_parallel_db(db, 1)

tensor([1, 1, 1,  ..., 0, 0, 0], dtype=torch.uint8)

In [3]:
def get_parallel_dbs(db):
    """Returns a list of all the possible parallel 
    databases of a given database
    
    Args:
        db (tensor): The original database.

    Returns:
        list: a list of pararllel databases.
    """
    parallel_dbs = list()
    
    # TODO: Create a list of parallel databases for every index
    for i in range(len(db)):
        pdb = get_parallel_db(db, i)
        parallel_dbs.append(pdb)
        
    return parallel_dbs

pdbs = get_parallel_dbs(db)
pdbs[:3]

[tensor([1, 1, 1,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 1,  ..., 0, 0, 0], dtype=torch.uint8),
 tensor([1, 1, 1,  ..., 0, 0, 0], dtype=torch.uint8)]

In [4]:
def create_db_and_parallels(num_entries):
    """Initializes a databes and creates a list of 
    all the possible parallel databases of itself
    
    Args:
        num_entries (int): length of the original database.

    Returns:
        db (tensor): the original database.
        pdbs (list): a list of pararllel databases.
    """
    # TODO: Initialize a database and all its parallel databases
    
    db = torch.rand(num_entries) > 0.5
    pdbs = get_parallel_dbs(db)
    
    return db, pdbs

db, pdbs = create_db_and_parallels(20)
db

tensor([1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1],
       dtype=torch.uint8)

# Project 2 - Evaluating the Privacy of a Function

In the last section, we measured the difference between each parallel db's query result and the query result for the entire database and then calculated the max value (which was 1). This value is called "sensitivity", and it corresponds to the function we chose for the query. Namely, the "sum" query will always have a sensitivity of exactly 1. However, we can also calculate sensitivity for other functions as well.

Let's try to calculate sensitivity for the "mean" function.

In [5]:
def query(db):
    """Queries the database by computing a mean"""
    return db.float().mean()

In [6]:
def sensitivity(query, n_entries=1000):
    """Computes the sensitivity of a given query
    for a particular database
    
    Args:
        query (fn): a function that queries the database.
        n_entries (int): size of the database.

    Returns:
        tensor: the resulting sensitivity.
    """
    # TODO: Create a custon database and its parallel databases
    db, pdbs = create_db_and_parallels(n_entries)
    
    # TODO: Query the full database
    full_db_result = query(db)
    
    # TODO: Loop through the parallel databases and compute the maximum sensitivity
    sensitivity = 0
    for pdb in pdbs:
        pdb_result = query(pdb)

        db_distance = torch.abs(pdb_result - full_db_result)

        if(db_distance > sensitivity):
            sensitivity = db_distance
            
    return sensitivity

In [7]:
sensitivity(query)

tensor(0.0005)

# Project 3: Calculate L1 Sensitivity For Threshold

In this first project, I want you to calculate the sensitivty for the "threshold" function. 

- First compute the sum over the database (i.e. sum(db)) and return whether that sum is greater than a certain threshold.
- Then, I want you to create databases of size 10 and threshold of 5 and calculate the sensitivity of the function. 
- Finally, re-initialize the database 10 times and calculate the sensitivity each time.

In [8]:
def query(db, threshold=5):
    """Computes the sum over a database and returns 
    whether that sum is greater than a certain threshold
    
    Args:
        db (tensor): randomly generated database.
        threshold (int): threshold to compare with query result.

    Returns:
        tensor: output of the query with threshold.
    """
    
    # TODO: Compute the sum over the database and check 
    # if it is graterer than the given threshold.
    
    return (db.sum() > threshold).float()

In [9]:
# TODO: create a database of size 10 and threshold of 5 and calculate the sensitivity of the function.
sensitivity(query, n_entries=10)

tensor(1.)

In [10]:
# TODO: re-initialize the database 10 times and calculate the sensitivity each time.
for i in range(10):
    sens_f = sensitivity(query, n_entries=10)
    print(sens_f)

0
tensor(1.)
0
tensor(1.)
0
0
tensor(1.)
0
tensor(1.)
0


# Project 4: Perform a Differencing Attack on Row 10

In this project, I want you to construct a database and then demonstrate how you can use two different sum queries to explose the value of the person represented by row 10 in the database (note, you'll need to use a database with at least 10 rows)

In [ ]:
# TODO: Construct a database with at least 10 rows
db = None

In [ ]:
# TODO: Get a parallel db by removing the 10th row
pdb = None

In [ ]:
# TODO: differencing attack using sum query


In [ ]:
# TODO: differencing attack using mean query


In [ ]:
# TODO: differencing attack using threshold
