## Project 1: Generate Parallel Databases

Key to the definition of differenital privacy is the ability to ask the question "When querying a database, if I removed someone from the database, would the output of the query be any different?". Thus, in order to check this, we must construct what we term "parallel databases" which are simply databases with one entry removed. 

In this first project, I want you to create a list of every parallel database to the one currently contained in the "db" variable. Then, I want you to create a function which both:

- creates the initial database (db)
- creates all parallel databases

In [2]:
import torch
# the number of entries in our database
num_entries = 5000
db = torch.rand(num_entries) > 0.5

In [3]:
def get_parallel_db(db, remove_index):
    """Returns a parallel database by removing
    one sample from a given index
    
    Args:
        db (tensor): The original database.
        remove_index (int): specifies which sample to remove.

    Returns:
        tensor: a pararllel database.
    """
    # TODO: Remove one sample from the database using the remove_index
    
    parallel_db = torch.cat((db[0:remove_index], 
                             db[remove_index+1:]))
    return parallel_db

get_parallel_db(db, 1)

tensor([0, 1, 0,  ..., 1, 1, 1], dtype=torch.uint8)

In [7]:
def get_parallel_dbs(db):
    """Returns a list of all the possible parallel 
    databases of a given database
    
    Args:
        db (tensor): The original database.

    Returns:
        list: a list of pararllel databases.
    """
    parallel_dbs = list()
    
    # TODO: Create a list of parallel databases for every index
    for i in range(len(db)):
        pdb = get_parallel_db(db, i)
        parallel_dbs.append(pdb)
        
    return parallel_dbs

pdbs = get_parallel_dbs(db)
pdbs[:3]

[tensor([0, 1, 0,  ..., 1, 1, 1], dtype=torch.uint8),
 tensor([0, 1, 0,  ..., 1, 1, 1], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 1, 1, 1], dtype=torch.uint8)]

In [9]:
def create_db_and_parallels(num_entries):
    """Initializes a databes and creates a list of 
    all the possible parallel databases of itself
    
    Args:
        num_entries (int): length of the original database.

    Returns:
        db (tensor): the original database.
        pdbs (list): a list of pararllel databases.
    """
    # TODO: Initialize a database and all its parallel databases
    
    db = torch.rand(num_entries) > 0.5
    pdbs = get_parallel_dbs(db)
    
    return db, pdbs

db, pdbs = create_db_and_parallels(20)
db

tensor([1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0],
       dtype=torch.uint8)